version: '3'

services:
  mysql_cake:
    image: mysql:5.7
    ports:
      - '3317:3306'
    volumes:
      - "cake_mysql_volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  php_cake:
    build:
      context: php7-fpm
      args:
        USER_UID: ${USER_UID}
    volumes:
      - "${ROOT_DIRECTORY}:/var/www/cake"
      - "cake_var_volume:/var/www/cake/var"
      - "~/.composer:/root/.composer"
    environment:
      XDEBUG_CONFIG: "remote_host=${YOUR_IP_ADDRESS}, client_host=${YOUR_IP_ADDRESS}"
      PHP_IDE_CONFIG: "serverName=${YOUR_HOST}"
  nginx_cake:
    build: nginx
    ports:
      - 8089:80
    volumes_from:
      - php_cake

volumes:
  cake_mysql_volume:
    external: true
  cake_var_volume:
    external: true
